version: '3.8'

services:
  ytmusicdl:
    image: lvgvspe2/ytmusicdl
    container_name: ytmusicdl_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /home/lucas/Músicas:/home/ytuser/Music
    environment:
      - PYTHONUNBUFFERED=1
      - TELEGRAM_TOKEN=<your_telegram_token>
      - TELEGRAM_CHATID=<your_telegram_chat_id>
    working_dir: /app
    user: "ytuser"
    stdin_open: true
    tty: true
